#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nextcloud-whiteboard"
name = "Nextcloud Whiteboard"
description.en = "The official whiteboard app for Nextcloud. Create and share whiteboards with real-time collaboration."
description.fr = "L'application de tableau blanc officielle pour Nextcloud. Créez et partagez des tableaux blancs avec une collaboration en temps réel."

version = "1.5.9~ynh1"

maintainers = [""]

[upstream]
license = "AGPL-3.0" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://apps.nextcloud.com/apps/whiteboard"
admindoc = "https://github.com/nextcloud/whiteboard?tab=readme-ov-file#installation--setup"
code = "https://github.com/nextcloud/whiteboard"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/whiteboard"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.nc_url]
    ask.en = "Nextcloud url"
    type = "string"
    example = "https://nextcloud.example.com"
    help = "The url of your Nextcloud instance."

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/nextcloud/whiteboard/archive/refs/tags/v1.5.9.tar.gz"
    sha256 = "35df7cac14ca69e34c183c9feee932ccfdaf1383406058480061c94db37164fc"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "redis-server, chromium, ffmpeg"

    [resources.nodejs]
    version = "24"
