location __PATH__/ {
    proxy_pass http://127.0.0.1:__PORT__/;

    include proxy_params_with_auth;

    proxy_read_timeout 86400;
    proxy_buffers 32 32k;
    proxy_busy_buffers_size 128k;

    client_max_body_size 1G;
}
